# NumPy แบบเร่งรัด
### @srakrn

## รู้จัก NumPy

NumPy เป็นไลบรารี่สำหรับการทำงานทางคณิตศาสตร์ที่ทรงพลัง หนึ่งในตัวอย่างที่ผู้เขียนมักหยิบมาเพื่อยกตัวอย่างความสามารถของ NumPy คือการดำเนินการทางเวกเตอร์ของ NumPy

หากเรามีเวกเตอร์ $\vec{u}=2\hat{i}+3\hat{j}+4\hat{k}$ และ $\vec{v}=3\hat{i}+4\hat{j}+5\hat{k}$ เราอาจเขียนแทนค่าของ $\vec{u}$ และ $\vec{v}$ ได้ด้วย Tuple ดังนี้

In [0]:
vec_u_tuple = (2, 3, 4)
vec_v_tuple = (3, 4, 5)

หากเราต้องการหาค่าของ $\vec{u}+\vec{v}$ เราจะพบว่าเมื่อเรานำตัวแปรทั้งสองตัวมาบวกกัน...

In [2]:
vec_u_tuple + vec_v_tuple

(2, 3, 4, 3, 4, 5)

จะกลายเป็นการทำ Tuple มาต่อกันแทน

## การนำเข้าโมดูล NumPy

การนำเข้าไลบรารี NumPy สามารถทำได้โดยใช้คำสั่ง

In [0]:
import numpy
# จะเห็นว่าใช้วิธีเดียวกับ import math เลย
import math

ซึ่งจะทำให้ได้ชุดคำสั่งจากไลบรารี NumPy ตามที่ต้องการ

## numpy.array

NumPy มาพร้อมชนิดข้อมูลหนึ่งตัวที่สำคัญนั่นคือ `numpy.array` เราสามารถแปลงลิสต์ หรือทูเปิลใดๆ ไปเป็น NumPy array ได้ด้วยการใช้คำสั่ง `numpy.array()` ครอบ (เช่นเดียวกับการแปลง int/float)

In [0]:
vec_u = numpy.array(vec_u_tuple)
vec_v = numpy.array(vec_v_tuple)

### การดำเนินการทางคณิตศาสตร์ของ NumPy array

เราจะพบว่าเมื่อเรานำ `vec_u` และ `vec_v` มาบวกกัน

In [5]:
vec_u + vec_v

array([5, 7, 9])

จะได้ค่าของ $\vec{u}+\vec{v}$ ตามที่ต้องการ นั่นหมายถึงว่าชนิดข้อมูล `numpy.array` ถูกออกแบบโดยเน้นการใช้งานทางคณิตศาสตร์เป็นหลัก

ในขณะเดียวกัน เราสามารถใช้ตัวดำเนินการ + - * / กับ `numpy.array` ได้ด้วย ซึ่งจะให้ผลเป็นการที่สมาชิกทุกตัวของ `numpy.array` ถูกกระทำ

In [6]:
vec_u

array([2, 3, 4])

In [7]:
vec_u + 2

array([4, 5, 6])

In [8]:
vec_u * 3

array([ 6,  9, 12])

### `numpy.arange()`

เราสามารถใช้คำสั่ง `numpy.arange()` สร้าง NumPy array ที่จะให้ผลลัพธ์ลักษณะเดียวกับ `range()` ของไพธอนได้

In [9]:
# สร้าง range ของ [1, 5) โดยเพิ่มขึ้นทีละ 0.2
numpy.arange(1, 5, 0.2)

array([ 1. ,  1.2,  1.4,  1.6,  1.8,  2. ,  2.2,  2.4,  2.6,  2.8,  3. ,
        3.2,  3.4,  3.6,  3.8,  4. ,  4.2,  4.4,  4.6,  4.8])

### array ขนาดหลายมิติ

ในขณะเดียวกัน NumPy array ไม่ได้จำกัดอยู่เพียงแค่ขนาดหนึ่งมิติ เราสามารถขยาย array ออกไปเป็นสอง หรือสามมิติได้ ตัวอย่างด้านล่างคือ array ขนาดสองมิติ

In [10]:
numpy.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

เราสามารถสร้าง array ขนาด n มิติของค่า 0 ได้ด้วยคำสั่ง `numpy.zeros()`

In [11]:
# สร้าง NumPy array ขนาด 2*3 ที่มีแต่ค่า 0
numpy.zeros([2, 3])

array([[ 0.,  0.,  0.],
       [ 0.,  0.,  0.]])

และสร้าง array ในรูปแบบเดียวกันของค่า 1 ได้ด้วยคำสั่ง `numpy.ones()`

In [12]:
# สร้าง NumPy array ขนาด 4*5 ที่มีแต่ค่า 1
numpy.ones([4, 5])

array([[ 1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.]])

ฟังก์ชั่นในการช่วยสร้าง NumPy array ยังมีอีกเยอะ เช่นฟังก์ชั่นด้านล่างนี้*เสก*เมทริกซ์เอกลักษณ์มาให้เราได้ทันที

In [13]:
numpy.identity(4)

array([[ 1.,  0.,  0.,  0.],
       [ 0.,  1.,  0.,  0.],
       [ 0.,  0.,  1.,  0.],
       [ 0.,  0.,  0.,  1.]])

### Slicing สำหรับ NumPy array

กำหนด `array_a` เป็นอาร์เรย์ของค่าด้านล่าง

In [0]:
array_a = numpy.array([
    [0.0, 0.1, 0.2, 0.3, 0.4],
    [1.0, 1.1, 1.2, 1.3, 1.4],
    [2.0, 2.1, 2.2, 2.3, 2.4],
    [3.0, 3.1, 3.2, 3.3, 3.4],
    [4.0, 4.1, 4.2, 4.3, 4.4]
])

# array_a = numpy.array([x+numpy.arange(0, 0.5, 0.1) for x in range(5)])

เราทราบดีอยู่แล้วว่าเราสามารถ slice ข้อมูลตามปกติในแบบไพธอนได้

In [15]:
array_a[0:2]

array([[ 0. ,  0.1,  0.2,  0.3,  0.4],
       [ 1. ,  1.1,  1.2,  1.3,  1.4]])

แต่หนึ่งในความสะดวกคือ เราสามารถ slice ข้อมูลในแนวตั้งได้ด้วย โดยใช้ `,` (comma) คั่น slicer

In [16]:
array_a[0:2, 1:4]

array([[ 0.1,  0.2,  0.3],
       [ 1.1,  1.2,  1.3]])