# NumPy แบบเร่งรัด
### @srakrn

## รู้จัก NumPy

NumPy เป็นไลบรารี่สำหรับการทำงานทางคณิตศาสตร์ที่ทรงพลัง หนึ่งในตัวอย่างที่ผู้เขียนมักหยิบมาเพื่อยกตัวอย่างความสามารถของ NumPy คือการดำเนินการทางเวกเตอร์ของ NumPy

หากเรามีเวกเตอร์ $\vec{u}=2\hat{i}+3\hat{j}+4\hat{k}$ และ $\vec{v}=3\hat{i}+4\hat{j}+5\hat{k}$ เราอาจเขียนแทนค่าของ $\vec{u}$ และ $\vec{v}$ ได้ด้วย Tuple ดังนี้

In [0]:
vec_u_tuple = (2, 3, 4)
vec_v_tuple = (3, 4, 5)

หากเราต้องการหาค่าของ $\vec{u}+\vec{v}$ เราจะพบว่าเมื่อเรานำตัวแปรทั้งสองตัวมาบวกกัน...

In [20]:
vec_u_tuple + vec_v_tuple

(2, 3, 4, 3, 4, 5)

จะกลายเป็นการทำ Tuple มาต่อกันแทน

## การนำเข้าโมดูล NumPy

การนำเข้าไลบรารี NumPy สามารถทำได้โดยใช้คำสั่ง

In [0]:
import numpy
# จะเห็นว่าใช้วิธีเดียวกับ import math เลย
import math

ซึ่งจะทำให้ได้ชุดคำสั่งจากไลบรารี NumPy ตามที่ต้องการ

## numpy.array

NumPy มาพร้อมชนิดข้อมูลหนึ่งตัวที่สำคัญนั่นคือ `numpy.array` เราสามารถแปลงลิสต์ หรือทูเปิลใดๆ ไปเป็น NumPy array ได้ด้วยการใช้คำสั่ง `numpy.array()` ครอบ (เช่นเดียวกับการแปลง int/float)

In [0]:
vec_u = numpy.array(vec_u_tuple)
vec_v = numpy.array(vec_v_tuple)

### การดำเนินการทางคณิตศาสตร์ของ NumPy array

เราจะพบว่าเมื่อเรานำ `vec_u` และ `vec_v` มาบวกกัน

In [23]:
vec_u + vec_v

array([5, 7, 9])

จะได้ค่าของ $\vec{u}+\vec{v}$ ตามที่ต้องการ นั่นหมายถึงว่าชนิดข้อมูล `numpy.array` ถูกออกแบบโดยเน้นการใช้งานทางคณิตศาสตร์เป็นหลัก

ในขณะเดียวกัน เราสามารถใช้ตัวดำเนินการ + - * / กับ `numpy.array` ได้ด้วย ซึ่งจะให้ผลเป็นการที่สมาชิกทุกตัวของ `numpy.array` ถูกกระทำ

In [24]:
vec_u

array([2, 3, 4])

In [25]:
vec_u + 2

array([4, 5, 6])

In [26]:
vec_u * 3

array([ 6,  9, 12])

### `numpy.arange()`

เราสามารถใช้คำสั่ง `numpy.arange()` สร้าง NumPy array ที่จะให้ผลลัพธ์ลักษณะเดียวกับ `range()` ของไพธอนได้

In [27]:
# สร้าง range ของ [1, 5) โดยเพิ่มขึ้นทีละ 0.2
numpy.arange(1, 5, 0.2)

array([ 1. ,  1.2,  1.4,  1.6,  1.8,  2. ,  2.2,  2.4,  2.6,  2.8,  3. ,
        3.2,  3.4,  3.6,  3.8,  4. ,  4.2,  4.4,  4.6,  4.8])

### array ขนาดหลายมิติ

ในขณะเดียวกัน NumPy array ไม่ได้จำกัดอยู่เพียงแค่ขนาดหนึ่งมิติ เราสามารถขยาย array ออกไปเป็นสอง หรือสามมิติได้ ตัวอย่างด้านล่างคือ array ขนาดสองมิติ

In [28]:
numpy.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

เราสามารถสร้าง array ขนาด n มิติของค่า 0 ได้ด้วยคำสั่ง `numpy.zeros()`

In [29]:
# สร้าง NumPy array ขนาด 2*3 ที่มีแต่ค่า 0
numpy.zeros([2, 3])

array([[ 0.,  0.,  0.],
       [ 0.,  0.,  0.]])

และสร้าง array ในรูปแบบเดียวกันของค่า 1 ได้ด้วยคำสั่ง `numpy.ones()`

In [30]:
# สร้าง NumPy array ขนาด 4*5 ที่มีแต่ค่า 1
numpy.ones([4, 5])

array([[ 1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.]])

ฟังก์ชั่นในการช่วยสร้าง NumPy array ยังมีอีกเยอะ เช่นฟังก์ชั่นด้านล่างนี้*เสก*เมทริกซ์เอกลักษณ์มาให้เราได้ทันที

In [31]:
numpy.identity(4)

array([[ 1.,  0.,  0.,  0.],
       [ 0.,  1.,  0.,  0.],
       [ 0.,  0.,  1.,  0.],
       [ 0.,  0.,  0.,  1.]])

### Slicing สำหรับ NumPy array

กำหนด `array_a` เป็นอาร์เรย์ของค่าด้านล่าง

In [0]:
array_a = numpy.array([
    [0.0, 0.1, 0.2, 0.3, 0.4],
    [1.0, 1.1, 1.2, 1.3, 1.4],
    [2.0, 2.1, 2.2, 2.3, 2.4],
    [3.0, 3.1, 3.2, 3.3, 3.4],
    [4.0, 4.1, 4.2, 4.3, 4.4]
])

# array_a = numpy.array([x+numpy.arange(0, 0.5, 0.1) for x in range(5)])

เราทราบดีอยู่แล้วว่าเราสามารถ slice ข้อมูลตามปกติในแบบไพธอนได้

In [33]:
array_a[0:2]

array([[ 0. ,  0.1,  0.2,  0.3,  0.4],
       [ 1. ,  1.1,  1.2,  1.3,  1.4]])

แต่หนึ่งในความสะดวกคือ เราสามารถ slice ข้อมูลในแนวตั้งได้ด้วย โดยใช้ `,` (comma) คั่น slicer

In [34]:
array_a[0:2, 1:4]

array([[ 0.1,  0.2,  0.3],
       [ 1.1,  1.2,  1.3]])

ดังนั้น เมื่อ slicer ของเรารองรับการ slice หลายมิติ เราอาจใช้ syntax การ slice ที่เหมือนมาจากภาษาอื่นมากกว่าไพธอนก็ได้ (ใช้ลักษณะนี้กับ list ไม่ได้)

(โค้ดด้านล่างจะมีปัญหาเรื่อง [floating point precision](https://th.wikipedia.org/wiki/%E0%B8%88%E0%B8%B3%E0%B8%99%E0%B8%A7%E0%B8%99%E0%B8%88%E0%B8%B8%E0%B8%94%E0%B8%A5%E0%B8%AD%E0%B8%A2%E0%B8%95%E0%B8%B1%E0%B8%A7))

In [35]:
array_a[3, 4]

3.3999999999999999

นอกจากนั้น เราสามารถยุบ NumPy array หลายมิติให้สามารถ iterate วนในอาร์เรย์ได้ ด้วย property `flat` หรือเมธอด `ravel()`

In [45]:
for i in array_a.flat:
  print(i)

0.0
0.1
0.2
0.3
0.4
1.0
1.1
1.2
1.3
1.4
2.0
2.1
2.2
2.3
2.4
3.0
3.1
3.2
3.3
3.4
4.0
4.1
4.2
4.3
4.4


In [46]:
array_a.ravel()

array([ 0. ,  0.1,  0.2,  0.3,  0.4,  1. ,  1.1,  1.2,  1.3,  1.4,  2. ,
        2.1,  2.2,  2.3,  2.4,  3. ,  3.1,  3.2,  3.3,  3.4,  4. ,  4.1,
        4.2,  4.3,  4.4])

## ฟังก์ชั่นทางคณิตศาสตร์ของ NumPy

NumPy มาพร้อมฟังก์ชั่นทางคณิตศาสตร์ซึ่งสามารถใช้กับ NumPy array ได้

In [43]:
sin_values = numpy.sin(numpy.arange(0, 4*math.pi, 0.5))
for i in sin_values:
  print(' '*(int(round(i*10))+10)+'*')

          *
               *
                  *
                    *
                   *
                *
           *
      *
  *
*
*
   *
       *
            *
                 *
                   *
                    *
                  *
              *
         *
     *
 *
*
 *
     *
         *


## ฟังก์ชั่นทางเมทริกซ์

เราทราบดีว่าเราสามารถสร้าง NumPy array แทนเมทริกซ์ได้

In [0]:
# สร้างเมทริกซ์เลขสุ่มของ [0, 1) ขนาด 4*4, คูณด้วย 10 แล้วแปลงเป็น int ทั้งหมด

matrix_a = (numpy.random.rand(4,4)*10).astype(int)
matrix_b = (numpy.random.rand(4,4)*10).astype(int)

In [62]:
matrix_a

array([[3, 4, 9, 1],
       [4, 4, 6, 0],
       [3, 8, 2, 8],
       [4, 1, 5, 2]])

In [63]:
matrix_b

array([[7, 1, 5, 5],
       [5, 1, 6, 8],
       [4, 4, 9, 4],
       [5, 5, 1, 4]])

เราสามารถเปลี่ยนขนาดของ NumPy array ได้ด้วยคำสั่ง `reshape()`

In [64]:
matrix_a.reshape(8, 2)

array([[3, 4],
       [9, 1],
       [4, 4],
       [6, 0],
       [3, 8],
       [2, 8],
       [4, 1],
       [5, 2]])

และหาทรานส์โพสของ NumPy array ได้ด้วยพารามิเตอร์ `T`

In [65]:
matrix_a.T

array([[3, 4, 3, 4],
       [4, 4, 8, 1],
       [9, 6, 2, 5],
       [1, 0, 8, 2]])

### การคูณเมทริกซ์

หากเราจับ `matrix_a * matrix_b` ตรงๆ เราจะได้ผลลัพธ์ของ A\*B เป็นการคูณเรียงตัว ($(A*B)_{ij} = A_{ij} \times B_{ij}$)

In [66]:
matrix_a * matrix_b

array([[21,  4, 45,  5],
       [20,  4, 36,  0],
       [12, 32, 18, 32],
       [20,  5,  5,  8]])

หากต้องการคูณเมทริกซ์ ให้ใช้คำสั่ง `numpy.dot()`

In [67]:
numpy.dot(matrix_a, matrix_b)

array([[ 82,  48, 121,  87],
       [ 72,  32,  98,  76],
       [109,  59,  89, 119],
       [ 63,  35,  73,  56]])

ในขณะเดียวกันก็มีคำสั่ง `numpy.cross()` สำหรับครอสเวกเตอร์เช่นกัน (ใม่ใช่ matrix แล้ว)

In [69]:
numpy.cross(vec_u, vec_v)
# ถ้าจำไม่ได้ว่า vec_u, vec_v มาจากไหน ให้ขึ้นไปบนสุด

array([-1,  2, -1])

### ดีเทอร์มิแนนท์ และอินเวิร์ส

ไลบรารี NumPy มีไลบรารีย่อย `numpy.linalg` สำหรับจัดการ linear algebra เป็นพิเศษ คำสั่งทางเมทริกซ์หลายคำสั่งอยู่ในไลบรารีย่อยนี้

สามารถหาดีเทอร์มิแนนท์ได้ด้วยคำสั่ง `numpy.linalg.det()` และหาอินเวิร์สได้ด้วยคำสั่ง `numpy.linalg.inv()`

In [70]:
numpy.linalg.det(matrix_a)

649.99999999999989

In [71]:
numpy.linalg.inv(matrix_a)

array([[-0.29538462,  0.27384615, -0.01538462,  0.20923077],
       [-0.01846154,  0.20461538,  0.06153846, -0.23692308],
       [ 0.20923077, -0.15230769, -0.03076923,  0.01846154],
       [ 0.07692308, -0.26923077,  0.07692308,  0.15384615]])

In [72]:
numpy.dot(matrix_a, numpy.linalg.inv(matrix_a))
# สังเกตว่าค่ามีความใกล้เคียงเมทริกซ์เอกลักษณ์ ที่ไม่เป๊ะเพราะ floating point precision

array([[  1.00000000e+00,   1.11022302e-16,   0.00000000e+00,
          5.55111512e-17],
       [ -5.55111512e-17,   1.00000000e+00,   0.00000000e+00,
          4.85722573e-17],
       [ -1.11022302e-16,   0.00000000e+00,   1.00000000e+00,
          0.00000000e+00],
       [ -3.33066907e-16,   1.11022302e-16,   2.77555756e-17,
          1.00000000e+00]])