# NumPy แบบเร่งรัด
### @srakrn

## ปรับปรุงเนื้อหา

รายการการปรับปรุงเนื้อหา เรียงตามวันที่
* 4 ธันวาคม 2560: เพิ่มเนื้อหาส่วนที่ออกสอบให้ละเอียดขึ้น (ครอบคลุมอยู่แล้ว แต่ไม่ละเอียดพอ), แจ้งเนื้อหาที่ไม่ออกสอบด้วยป้าย `[ไม่ออกสอบ]` ในหัวข้อ

ดังนั้น โดยสรุปแล้ว เนื้อหาที่ออกสอบปลายภาค มีแค่
* การสร้าง NumPy array ด้วยการเปลี่ยนจาก list เป็น NumPy array
* การสร้าง NumPy array ด้วย `numpy.arange()`
* การใช้ `ufunc` (เช่น ฟังก์ชั่นบวก ลบ คูณ หาร) กับ NumPy array

จะเห็นว่าเนื้อหาออกสอบจริงน้อยกว่าที่ผู้เขียนคาดการณ์มาก

---

## รู้จัก NumPy

NumPy เป็นไลบรารี่สำหรับการทำงานทางคณิตศาสตร์ที่ทรงพลัง หนึ่งในตัวอย่างที่ผู้เขียนมักหยิบมาเพื่อยกตัวอย่างความสามารถของ NumPy คือการดำเนินการทางเวกเตอร์ของ NumPy

หากเรามีเวกเตอร์ $\vec{u}=2\hat{i}+3\hat{j}+4\hat{k}$ และ $\vec{v}=3\hat{i}+4\hat{j}+5\hat{k}$ เราอาจเขียนแทนค่าของ $\vec{u}$ และ $\vec{v}$ ได้ด้วย Tuple ดังนี้

In [0]:
vec_u_tuple = (2, 3, 4)
vec_v_tuple = (3, 4, 5)

หากเราต้องการหาค่าของ $\vec{u}+\vec{v}$ เราจะพบว่าเมื่อเรานำตัวแปรทั้งสองตัวมาบวกกัน...

In [2]:
vec_u_tuple + vec_v_tuple

(2, 3, 4, 3, 4, 5)

จะกลายเป็นการทำ Tuple มาต่อกันแทน

## การนำเข้าโมดูล NumPy

การนำเข้าไลบรารี NumPy สามารถทำได้โดยใช้คำสั่ง

In [0]:
import numpy
# จะเห็นว่าใช้วิธีเดียวกับ import math เลย
import math

ซึ่งจะทำให้ได้ชุดคำสั่งจากไลบรารี NumPy ตามที่ต้องการ

## numpy.array

NumPy มาพร้อมชนิดข้อมูลหนึ่งตัวที่สำคัญนั่นคือ `numpy.array` เราสามารถแปลงลิสต์ หรือทูเปิลใดๆ ไปเป็น NumPy array ได้ด้วยการใช้คำสั่ง `numpy.array()` ครอบ (เช่นเดียวกับการแปลง int/float)

In [0]:
vec_u = numpy.array(vec_u_tuple)
vec_v = numpy.array(vec_v_tuple)

### การดำเนินการทางคณิตศาสตร์ของ NumPy array

เราจะพบว่าเมื่อเรานำ `vec_u` และ `vec_v` มาบวกกัน

In [5]:
vec_u + vec_v

array([5, 7, 9])

จะได้ค่าของ $\vec{u}+\vec{v}$ ตามที่ต้องการ นั่นหมายถึงว่าชนิดข้อมูล `numpy.array` ถูกออกแบบโดยเน้นการใช้งานทางคณิตศาสตร์เป็นหลัก

ในขณะเดียวกัน เราสามารถใช้ตัวดำเนินการ + - * / กับ `numpy.array` ได้ด้วย ซึ่งจะให้ผลเป็นการที่สมาชิกทุกตัวของ `numpy.array` ถูกกระทำ

In [6]:
vec_u

array([2, 3, 4])

In [7]:
vec_u + 2

array([4, 5, 6])

In [8]:
vec_u * 3

array([ 6,  9, 12])

### `numpy.arange()`

เราสามารถใช้คำสั่ง `numpy.arange()` สร้าง NumPy array ที่จะให้ผลลัพธ์ลักษณะเดียวกับ `range()` ของไพธอนได้

In [9]:
# สร้าง range ของ [1, 5) โดยเพิ่มขึ้นทีละ 0.2
numpy.arange(1, 5, 0.2)

array([ 1. ,  1.2,  1.4,  1.6,  1.8,  2. ,  2.2,  2.4,  2.6,  2.8,  3. ,
        3.2,  3.4,  3.6,  3.8,  4. ,  4.2,  4.4,  4.6,  4.8])

### array ขนาดหลายมิติ

ในขณะเดียวกัน NumPy array ไม่ได้จำกัดอยู่เพียงแค่ขนาดหนึ่งมิติ เราสามารถขยาย array ออกไปเป็นสอง หรือสามมิติได้ ตัวอย่างด้านล่างคือ array ขนาดสองมิติ

In [10]:
numpy.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

#### ตัวช่วยสร้าง array [ไม่ออกสอบ]

เราสามารถสร้าง array ขนาด n มิติของค่า 0 ได้ด้วยคำสั่ง `numpy.zeros()`

In [11]:
# สร้าง NumPy array ขนาด 2*3 ที่มีแต่ค่า 0
numpy.zeros([2, 3])

array([[ 0.,  0.,  0.],
       [ 0.,  0.,  0.]])

และสร้าง array ในรูปแบบเดียวกันของค่า 1 ได้ด้วยคำสั่ง `numpy.ones()`

In [12]:
# สร้าง NumPy array ขนาด 4*5 ที่มีแต่ค่า 1
numpy.ones([4, 5])

array([[ 1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.]])

ฟังก์ชั่นในการช่วยสร้าง NumPy array ยังมีอีกเยอะ เช่นฟังก์ชั่นด้านล่างนี้*เสก*เมทริกซ์เอกลักษณ์มาให้เราได้ทันที

In [13]:
numpy.identity(4)

array([[ 1.,  0.,  0.,  0.],
       [ 0.,  1.,  0.,  0.],
       [ 0.,  0.,  1.,  0.],
       [ 0.,  0.,  0.,  1.]])

### Slicing สำหรับ NumPy array [ไม่ออกสอบ]

กำหนด `array_a` เป็นอาร์เรย์ของค่าด้านล่าง

In [0]:
array_a = numpy.array([
    [0.0, 0.1, 0.2, 0.3, 0.4],
    [1.0, 1.1, 1.2, 1.3, 1.4],
    [2.0, 2.1, 2.2, 2.3, 2.4],
    [3.0, 3.1, 3.2, 3.3, 3.4],
    [4.0, 4.1, 4.2, 4.3, 4.4]
])

# array_a = numpy.array([x+numpy.arange(0, 0.5, 0.1) for x in range(5)])

เราทราบดีอยู่แล้วว่าเราสามารถ slice ข้อมูลตามปกติในแบบไพธอนได้

In [15]:
array_a[0:2]

array([[ 0. ,  0.1,  0.2,  0.3,  0.4],
       [ 1. ,  1.1,  1.2,  1.3,  1.4]])

แต่หนึ่งในความสะดวกคือ เราสามารถ slice ข้อมูลในแนวตั้งได้ด้วย โดยใช้ `,` (comma) คั่น slicer

In [16]:
array_a[0:2, 1:4]

array([[ 0.1,  0.2,  0.3],
       [ 1.1,  1.2,  1.3]])

ดังนั้น เมื่อ slicer ของเรารองรับการ slice หลายมิติ เราอาจใช้ syntax การ slice ที่เหมือนมาจากภาษาอื่นมากกว่าไพธอนก็ได้ (ใช้ลักษณะนี้กับ list ไม่ได้)

(โค้ดด้านล่างจะมีปัญหาเรื่อง [floating point precision](https://th.wikipedia.org/wiki/%E0%B8%88%E0%B8%B3%E0%B8%99%E0%B8%A7%E0%B8%99%E0%B8%88%E0%B8%B8%E0%B8%94%E0%B8%A5%E0%B8%AD%E0%B8%A2%E0%B8%95%E0%B8%B1%E0%B8%A7))

In [17]:
array_a[3, 4]

3.3999999999999999

นอกจากนั้น เราสามารถยุบ NumPy array หลายมิติให้สามารถ iterate วนในอาร์เรย์ได้ ด้วย property `flat` หรือเมธอด `ravel()`

In [18]:
for i in array_a.flat:
  print(i)

0.0
0.1
0.2
0.3
0.4
1.0
1.1
1.2
1.3
1.4
2.0
2.1
2.2
2.3
2.4
3.0
3.1
3.2
3.3
3.4
4.0
4.1
4.2
4.3
4.4


In [19]:
array_a.ravel()

array([ 0. ,  0.1,  0.2,  0.3,  0.4,  1. ,  1.1,  1.2,  1.3,  1.4,  2. ,
        2.1,  2.2,  2.3,  2.4,  3. ,  3.1,  3.2,  3.3,  3.4,  4. ,  4.1,
        4.2,  4.3,  4.4])

## ฟังก์ชั่นทางคณิตศาสตร์ของ NumPy

NumPy มาพร้อมฟังก์ชั่นทางคณิตศาสตร์ซึ่งสามารถใช้กับ NumPy array ได้

In [20]:
m = numpy.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])
# m = numpy.arange(9).reshape((3, 3))+1

n = numpy.array([
    [9, 8, 7],
    [6, 5, 4],
    [3, 2, 1]
])
# n = numpy.arange(9, -1, -1).reshape((3, 3))

print(numpy.add(m, n))
# ที่จริงจะ print(m+n) เลยก็ได้

[[10 10 10]
 [10 10 10]
 [10 10 10]]


In [21]:
o = numpy.arange(0, 4.1, 0.2) * math.pi
# o = [0, 0.2*pi, 0.4*pi, ..., 2*pi]

sin_values = numpy.sin(o)
print(sin_values)

[  0.00000000e+00   5.87785252e-01   9.51056516e-01   9.51056516e-01
   5.87785252e-01   1.22464680e-16  -5.87785252e-01  -9.51056516e-01
  -9.51056516e-01  -5.87785252e-01  -2.44929360e-16   5.87785252e-01
   9.51056516e-01   9.51056516e-01   5.87785252e-01   3.67394040e-16
  -5.87785252e-01  -9.51056516e-01  -9.51056516e-01  -5.87785252e-01
  -4.89858720e-16]


In [22]:
for sin_value in sin_values:
  print(" "*(int(sin_value*5)+5) + "*")
  
# แสดงผลกราฟ sin แนวตั้ง จากค่า sin ที่คิดได้

     *
       *
         *
         *
       *
     *
   *
 *
 *
   *
     *
       *
         *
         *
       *
     *
   *
 *
 *
   *
     *


เราเรียกฟังก์ชั่นเหล่านี้ว่า `ufunc` (Universal functions) ซึ่งมีฟังก์ชั่นที่น่าสนใจ (หรือกล่าวได้ว่าใช้บ่อย) ดังนี้
* add
* subtract
* multiply
* divide
* mod
* sqrt
* sin
* cos
* tan
* arcsin
* arccos
* arctan

หากสนใจสามารถดูรายการ `ufunc` ทั้งหมดที่มีได้[ที่นี่](https://docs.scipy.org/doc/numpy-1.13.0/reference/ufuncs.html#available-ufuncs)

## ฟังก์ชั่นทางเมทริกซ์ [ไม่ออกสอบ]

เราทราบดีว่าเราสามารถสร้าง NumPy array แทนเมทริกซ์ได้

In [0]:
# สร้างเมทริกซ์เลขสุ่มของ [0, 1) ขนาด 4*4, คูณด้วย 10 แล้วแปลงเป็น int ทั้งหมด

matrix_a = (numpy.random.rand(4,4)*10).astype(int)
matrix_b = (numpy.random.rand(4,4)*10).astype(int)

In [24]:
matrix_a

array([[4, 9, 2, 0],
       [5, 2, 6, 3],
       [9, 8, 7, 9],
       [9, 5, 9, 4]])

In [25]:
matrix_b

array([[9, 2, 0, 1],
       [9, 3, 1, 5],
       [4, 3, 9, 5],
       [6, 8, 8, 5]])

เราสามารถเปลี่ยนขนาดของ NumPy array ได้ด้วยคำสั่ง `reshape()`

In [26]:
matrix_a.reshape(8, 2)

array([[4, 9],
       [2, 0],
       [5, 2],
       [6, 3],
       [9, 8],
       [7, 9],
       [9, 5],
       [9, 4]])

และหาทรานส์โพสของ NumPy array ได้ด้วยพารามิเตอร์ `T`

In [27]:
matrix_a.T

array([[4, 5, 9, 9],
       [9, 2, 8, 5],
       [2, 6, 7, 9],
       [0, 3, 9, 4]])

### การคูณเมทริกซ์ [ไม่ออกสอบ]

หากเราจับ `matrix_a * matrix_b` ตรงๆ เราจะได้ผลลัพธ์ของ A\*B เป็นการคูณเรียงตัว ($(A*B)_{ij} = A_{ij} \times B_{ij}$)

In [28]:
matrix_a * matrix_b

array([[36, 18,  0,  0],
       [45,  6,  6, 15],
       [36, 24, 63, 45],
       [54, 40, 72, 20]])

หากต้องการคูณเมทริกซ์ ให้ใช้คำสั่ง `numpy.dot()`

In [29]:
numpy.dot(matrix_a, matrix_b)

array([[125,  41,  27,  59],
       [105,  58,  80,  60],
       [235, 135, 143, 129],
       [186,  92, 118,  99]])

ในขณะเดียวกันก็มีคำสั่ง `numpy.cross()` สำหรับครอสเวกเตอร์เช่นกัน (ใม่ใช่ matrix แล้ว)

In [30]:
numpy.cross(vec_u, vec_v)
# ถ้าจำไม่ได้ว่า vec_u, vec_v มาจากไหน ให้ขึ้นไปบนสุด

array([-1,  2, -1])

### ดีเทอร์มิแนนท์ และอินเวิร์ส [ไม่ออกสอบ]

ไลบรารี NumPy มีไลบรารีย่อย `numpy.linalg` สำหรับจัดการ linear algebra เป็นพิเศษ คำสั่งทางเมทริกซ์หลายคำสั่งอยู่ในไลบรารีย่อยนี้

สามารถหาดีเทอร์มิแนนท์ได้ด้วยคำสั่ง `numpy.linalg.det()` และหาอินเวิร์สได้ด้วยคำสั่ง `numpy.linalg.inv()`

In [31]:
numpy.linalg.det(matrix_a)

-310.99999999999966

In [32]:
numpy.linalg.inv(matrix_a)

array([[-0.26688103, -1.45016077,  0.04180064,  0.99356913],
       [ 0.18971061,  0.39228296,  0.00643087, -0.30868167],
       [ 0.18006431,  1.13504823, -0.11254019, -0.59807074],
       [-0.04180064,  0.21864952,  0.1511254 , -0.25401929]])

In [33]:
numpy.dot(matrix_a, numpy.linalg.inv(matrix_a))
# สังเกตว่าค่ามีความใกล้เคียงเมทริกซ์เอกลักษณ์ ที่ไม่เป๊ะเพราะ floating point precision

array([[  1.00000000e+00,  -1.33226763e-15,   5.55111512e-17,
          2.22044605e-16],
       [  1.94289029e-16,   1.00000000e+00,  -8.32667268e-17,
         -3.88578059e-16],
       [  8.32667268e-17,  -5.82867088e-16,   1.00000000e+00,
         -2.77555756e-16],
       [  8.32667268e-17,  -1.22124533e-15,  -1.11022302e-16,
          1.00000000e+00]])